create or replace view public.volunteer_registrations_export as
select
  id,
  created_at,
  submitted_at,
  source,
  full_name,
  email,
  phone,
  facebook_or_zalo,
  array_to_string(selected_activities, ' | ') as selected_activities_text,
  array_to_string(selected_departments, ' | ') as selected_departments_text,
  payload->>'dateOfBirth' as date_of_birth,
  payload->>'schoolInfo' as school_info,
  payload->>'aboutLuom' as about_luom,
  payload->>'motivation' as motivation,
  payload->>'generalStrengthsOther' as general_strengths_other,
  payload->>'previousVolunteerExperience' as previous_volunteer_experience,
  payload->>'techRole' as tech_role,
  array_to_string(array(select jsonb_array_elements_text(payload->'techFields')), ' | ') as tech_fields_text,
  payload->>'techAiSkills' as tech_ai_skills,
  payload->>'techTeachingTools' as tech_teaching_tools,
  array_to_string(array(select jsonb_array_elements_text(payload->'mediaPositions')), ' | ') as media_positions_text,
  payload->>'portfolioUrl' as portfolio_url,
  payload->>'mediaWritingChallenge' as media_writing_challenge,
  payload->>'mediaDesignPortfolioNote' as media_design_portfolio_note,
  payload->>'mediaVideoPortfolioNote' as media_video_portfolio_note,
  payload->>'mediaHasCamera' as media_has_camera,
  array_to_string(array(select jsonb_array_elements_text(payload->'supportTasks')), ' | ') as support_tasks_text,
  payload->>'availableForGreenCamp' as available_for_green_camp,
  payload->>'priority1' as priority_1,
  payload->>'priority2' as priority_2,
  payload->>'priority3' as priority_3,
  payload
from public.volunteer_registrations
order by submitted_at desc;
